# -*- coding: utf-8 -*-
"""Ubuntu_Requests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0krpLTQGarCLs08yCNad9zmRF_eScmy
"""

import requests
import os
from urllib.parse import urlparse

def main():
  print('Welcome to the Ubuntu photo studio')
  print('A place to jog your mind')

  # Get url from user
  url = input('Enter the image URL: ')
  try:
    # Create directory if it does not exist
    os.makedirs('Fetched_Images', exist_ok=True)
    # Fetch the image
    response = requests.get(url, timeout = 10)
    response.raise_for_status()
    # Extract filename from url or generate one
    parsed_url = urlparse(url)
    filename = os.path.basename(parsed_url.path)
    if not filename:
        filename = 'downloaded_image.jpg' # Default filename if none found in URL

    filepath = os.path.join("Fetched_Images", filename)

    # Save the image in binary mode
    with open(filepath, 'wb') as f:
        f.write(response.content)

    print(f"Image downloaded successfully to {filepath}")

  except requests.exceptions.RequestException as e:
    print(f"Error fetching the image: {e}")
  except Exception as e:
    print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
  main()